# Generated by Django 5.0.2 on 2024-02-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nagruzka',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=123, null=True)),
                ('group_id', models.ManyToManyField(to='group.groupp', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherr', to='teacher.teacher', verbose_name='Преподователь')),
            ],
            options={
                'verbose_name': 'Нагрузка',
                'verbose_name_plural': 'Нагрузки',
            },
        ),
    ]
