# Generated by Django 5.0.2 on 2024-05-20 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_options'),
        ('nagr', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nagruzka',
            name='group_id',
        ),
        migrations.AddField(
            model_name='nagruzka',
            name='group_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='group.groupp', verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
