# Generated by Django 4.0.3 on 2022-10-17 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0003_remove_groupp_for_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='for_discipline',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='discipline_group', to='nagr.discipline', verbose_name='Дисциплина'),
            preserve_default=False,
        ),
    ]
