# Generated by Django 5.0.2 on 2024-05-20 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0003_teachersummary'),
    ]

    operations = [

    ]
