# Generated by Django 5.0.2 on 2024-05-20 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0005_alter_teachersummary_teacher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeacherSummary',
        ),
    ]
