# Generated by Django 5.0.2 on 2024-05-20 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0006_delete_teachersummary'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSummary',
            fields=[
                ('teacher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='teacher.teacher')),
                ('total_lekcii_po_ucheb_planu', models.IntegerField(default=0, verbose_name='Всего лекций по учебному плану')),
                ('total_praktZan_po_ucheb_planu', models.IntegerField(default=0, verbose_name='Всего практических занятий по учебному плану')),
                ('total_labRab_po_ucheb_planu', models.IntegerField(default=0, verbose_name='Всего лабораторных работ по учебному плану')),
                ('total_rukovod_KRIKP', models.IntegerField(default=0, verbose_name='Всего руководство КРиКП')),
                ('total_recenzirov_KR', models.IntegerField(default=0, verbose_name='Всего рецензирование КР')),
                ('total_priem_SRS', models.FloatField(default=0.0, verbose_name='Всего прием СРС')),
                ('total_praktika_uchebnay', models.IntegerField(default=0, verbose_name='Всего учебная практика')),
                ('total_praktika_proizvod', models.IntegerField(default=0, verbose_name='Всего производственная практика')),
                ('total_praktika_predkval', models.IntegerField(default=0, verbose_name='Всего предквалификационная практика')),
                ('total_praktika_pedagog', models.IntegerField(default=0, verbose_name='Всего педагогическая практика')),
                ('total_praktika_nauchno', models.IntegerField(default=0, verbose_name='Всего научно-исследовательская практика')),
                ('total_kontrol_itogovyi', models.FloatField(default=0.0, verbose_name='Всего итоговый контроль (экзамен)')),
                ('total_zachita_rukovod_VKR', models.FloatField(default=0.0, verbose_name='Всего руководство ВКР')),
                ('total_zachita_konsult', models.FloatField(default=0.0, verbose_name='Всего консультирование по разделам')),
                ('total_zachita_recencirovanie', models.FloatField(default=0.0, verbose_name='Всего рецензирование')),
                ('total_zachita_uchastie_v_GAK', models.FloatField(default=0.0, verbose_name='Всего участие в ГАК')),
                ('total_normokontr', models.FloatField(default=0.0, verbose_name='Всего нормоконтроль')),
                ('total_magistratura', models.FloatField(default=0.0, verbose_name='Всего магистратура')),
                ('total_aspirantura_doctorontura', models.FloatField(default=0.0, verbose_name='Всего аспирантура, докторантура')),
                ('total_academ_sov', models.FloatField(default=0.0, verbose_name='Всего академический совет')),
                ('total_rukovodstvo_kafedroi', models.FloatField(default=0.0, verbose_name='Всего руководство кафедрой')),
                ('total_vsego_uchebnyh_chasov', models.FloatField(default=0.0, verbose_name='Всего учебных часов')),
                ('total_za_vsego_uchebnyh_chasov', models.FloatField(default=0.0, verbose_name='Всего учебных часов заочно')),
            ],
            options={
                'verbose_name': 'Суммированные данные учителя',
                'verbose_name_plural': 'Суммированные данные учителей',
                'managed': True,
            },
        ),
    ]
