# Generated by Django 4.0.3 on 2022-10-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0006_groupp_for_discipline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='discipline_id',
        ),
    ]
