# Generated by Django 4.0.3 on 2022-10-20 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0007_remove_connect_discipline_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='for_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disciplinee', to='nagr.discipline'),
        ),
    ]
