# Generated by Django 5.0.2 on 2024-05-20 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0007_teachersummary'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teachersummary',
            options={'managed': True, 'verbose_name': 'Сводная ведомость', 'verbose_name_plural': 'Сводные ведомости'},
        ),
    ]
