# Generated by Django 5.0.2 on 2024-05-21 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0008_alter_teachersummary_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_academ_sov',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_aspirantura_doctorontura',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_kontrol_itogovyi',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_labRab_po_ucheb_planu',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_lekcii_po_ucheb_planu',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_magistratura',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_normokontr',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktZan_po_ucheb_planu',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktika_nauchno',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktika_pedagog',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktika_predkval',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktika_proizvod',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_praktika_uchebnay',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_priem_SRS',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_recenzirov_KR',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_rukovod_KRIKP',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_rukovodstvo_kafedroi',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_vsego_uchebnyh_chasov',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_za_vsego_uchebnyh_chasov',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_zachita_konsult',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_zachita_recencirovanie',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_zachita_rukovod_VKR',
        ),
        migrations.RemoveField(
            model_name='teachersummary',
            name='total_zachita_uchastie_v_GAK',
        ),
    ]
