# Generated by Django 4.0.3 on 2022-10-20 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0008_alter_groupp_for_discipline'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='discipline_id',
            field=models.ManyToManyField(to='nagr.discipline'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='for_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagr.discipline'),
        ),
    ]
