# Generated by Django 5.0.2 on 2024-05-21 13:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0009_remove_teachersummary_total_academ_sov_and_more'),
        ('teacher', '0004_alter_teacher_options_remove_teacher_stavka_zaoch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagruzka',
            name='name',
            field=models.CharField(blank=True, max_length=123, null=True, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='teachersummary',
            name='teacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='summary', serialize=False, to='teacher.teacher', verbose_name='Преподователь'),
        ),
    ]
