# Generated by Django 4.1.2 on 2022-10-23 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0009_connect_discipline_id_alter_groupp_for_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='for_discipline',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagr.discipline', verbose_name='Дисциплины: '),
        ),
    ]
