# Generated by Django 4.1.2 on 2022-10-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0010_alter_groupp_for_discipline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название группы: '),
        ),
    ]
