# Generated by Django 5.0.2 on 2024-05-22 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0010_alter_nagruzka_name_alter_teachersummary_teacher'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nagruzka',
            options={'verbose_name': 'Распределение нагрузки', 'verbose_name_plural': 'Распределение нагрузки'},
        ),
    ]
