# Generated by Django 4.1.2 on 2022-10-23 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0012_alter_discipline_name_alter_teacher_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connect',
            name='discipline_id',
            field=models.ManyToManyField(to='nagr.discipline', verbose_name='Дисциплина'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='group_id',
            field=models.ManyToManyField(to='nagr.groupp', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='connect',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherr', to='nagr.teacher', verbose_name='Преподователь'),
        ),
    ]
