# Generated by Django 4.1.2 on 2022-10-23 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0013_alter_connect_discipline_id_alter_connect_group_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='academ_sov',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Академ. сов'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='aspi_doctoron',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Аспирантура, докторонтура'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='itogo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итого по бюджету'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='itogo2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ИТОГО'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='itogo_kontr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итого по контракту'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='itogo_pochasovoi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ИТОГО почасовой фонд'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='itovyi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итоговый (экзамен)'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[(1, 'проф(1ст)'), (2, 'ст.преп(1cт)'), (3, 'проф.'), (4, 'доцент'), (5, 'преп.')], max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='laby',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Лабораторные'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='lekcii',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Лекции'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='magistratura',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Магистратура'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='normokontr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Нормоконтр'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='ofline',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Офлайн'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='online',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Онлайн'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pochasovoi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Почасовой фонд бюджет'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='pochasovoi_fond_kontract',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Почасвой фонд контракт'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практические'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika_nauchno',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Научно-исследовательская'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika_pedagog',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Педагогическая'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika_predkval',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Предквалификационная'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika_proizvod',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Производственная'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='praktika_ucheb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Учебная'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='priem_SRS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прием СРС'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='recenzirov_KR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рецензиров. КР'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rikovod_dek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство деканатом'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rukovod_KRIKP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руковод. КРиКП'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='rukovod_kaf',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство кафедрой'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vsego',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Всего'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zachita_consult',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/консульт. по разделам'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zachita_recenzirovanie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/рецензирование'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zachita_rukovod_VKR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/Руководство ВКР'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zachita_uchastie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/участие в ГАК'),
        ),
    ]
