# Generated by Django 4.0.3 on 2022-10-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0015_remove_groupp_academ_sov_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='labRab_po_ucheb_planu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лаб.раб/ По учебному плану'),
        ),
        migrations.AlterField(
            model_name='group',
            name='labRab_zachityvaetsa_v_nagruzku',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лаб.раб/ Зачитывается в нагрузку кафедры (ч.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='lekcii_po_ucheb_planu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лекции/ По учебному плану'),
        ),
        migrations.AlterField(
            model_name='group',
            name='lekcii_zachityvaetsa_v_nagruzku',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Лекции/ Зачитывается в нагрузку кафедры (ч.)'),
        ),
        migrations.AlterField(
            model_name='group',
            name='praktZan_po_ucheb_planu',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практ.зан/ По учебному плану'),
        ),
        migrations.AlterField(
            model_name='group',
            name='praktZan_zachityvaetsa_v_nagruzku',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практ.зан/ Зачитывается в нагрузку кафедры (ч.)'),
        ),
    ]
