# Generated by Django 4.0.3 on 2022-10-26 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0017_groupp_discipline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='discipline',
            name='is_kursovoi',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='groupp',
            name='is_kursovoi',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
