# Generated by Django 4.0.3 on 2022-10-30 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0021_group_teacher_alter_group_name_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='teacher',
        ),
    ]
