# Generated by Django 4.0.3 on 2022-10-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0022_remove_group_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='discipline_id',
        ),
        migrations.AlterField(
            model_name='connect',
            name='group_id',
            field=models.ManyToManyField(to='nagr.group', verbose_name='Группа'),
        ),
    ]
