# Generated by Django 4.0.3 on 2022-11-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0024_group_discipline_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discipline',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='groupp',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, choices=[(1, 'профессор'), (2, 'доцент'), (3, 'старший преподователь'), (4, 'преподователь')], max_length=250, null=True, verbose_name='Должность'),
        ),
    ]
