# Generated by Django 4.0.3 on 2022-11-05 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0027_connect_doljnost_connect_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='academ_sov',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='aspi_doctoron',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='doljnost',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='itovyi',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='laby',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='lekcii',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='magistratura',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='normokontr',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='ofline',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='online',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika_nauchno',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika_pedagog',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika_predkval',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika_proizvod',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='praktika_ucheb',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='priem_SRS',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='recenzirov_KR',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='rikovod_dek',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='rukovod_KRIKP',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='rukovod_kaf',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='vsego',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='zachita_consult',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='zachita_recenzirovanie',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='zachita_rukovod_VKR',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='zachita_uchastie',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность'),
        ),
    ]
