# Generated by Django 4.0.3 on 2022-11-11 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0029_alter_teacher_is_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='itogo',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='itogo2',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='itogo_kontr',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='itogo_pochasovoi',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='pochasovoi',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='pochasovoi_fond_kontract',
        ),
        migrations.AddField(
            model_name='connect',
            name='shtatnye_budget',
            field=models.FloatField(default=0, verbose_name='Штатные единицы/Бюджет'),
        ),
        migrations.AddField(
            model_name='connect',
            name='shtatnye_contract_ochnoe',
            field=models.FloatField(default=0, verbose_name='Штатные единицы/контракт/очное'),
        ),
        migrations.AddField(
            model_name='connect',
            name='shtatnye_contract_zaochnoe',
            field=models.FloatField(default=0, verbose_name='Штатные единицы/контракт/заочное'),
        ),
        migrations.AddField(
            model_name='connect',
            name='shtatnye_vsego',
            field=models.FloatField(default=0, verbose_name='Штатные единицы/Всего'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ucheb_budget',
            field=models.FloatField(default=0, verbose_name='Учебная нагрузка/Бюджет'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ucheb_contract_ochnoe',
            field=models.FloatField(default=0, verbose_name='Учебная нагрузка/контракт/очное'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ucheb_contract_zaochnoe',
            field=models.FloatField(default=0, verbose_name='Учебная нагрузка/контракт/заочное'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ucheb_vsego',
            field=models.FloatField(default=0, verbose_name='Учебная нагрузка/Всего'),
        ),
    ]
