# Generated by Django 4.0.3 on 2022-12-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0032_coppect_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coppect',
            name='is_budget',
            field=models.BooleanField(default=False, verbose_name='Бюджетный'),
        ),
    ]
