# Generated by Django 4.0.3 on 2022-12-04 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0033_coppect_is_budget'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coppect',
            old_name='group_id',
            new_name='grouppp',
        ),
    ]
