# Generated by Django 4.0.3 on 2022-12-04 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0034_rename_group_id_coppect_grouppp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coppect',
            name='stavka',
            field=models.FloatField(default=1, verbose_name='Ставка'),
            preserve_default=False,
        ),
    ]
