# Generated by Django 4.0.3 on 2022-12-04 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0036_alter_coppect_shtatnye_budget_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coppect',
        ),
    ]
