# Generated by Django 4.0.3 on 2022-12-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0037_delete_coppect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Название дисциплины: '),
        ),
    ]
