# Generated by Django 4.0.3 on 2022-12-09 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0038_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.IntegerField(blank=True, choices=[(1, 'Профессор'), (2, 'Доцент'), (3, 'Старший преподователь'), (4, 'Преподователь')], null=True, verbose_name='Звание'),
        ),
    ]
