# Generated by Django 4.0.3 on 2022-12-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0039_alter_teacher_zvanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.IntegerField(blank=True, choices=[(1, 'Профессор'), (2, 'Доцент'), (3, 'Старший преподователь'), (4, 'Преподователь')], null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Звание'),
        ),
    ]
