# Generated by Django 4.0.3 on 2022-12-10 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0041_alter_teacher_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='name',
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(default=1, max_length=20, verbose_name='Имя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default=0, max_length=30, verbose_name='Фамилия'),
            preserve_default=False,
        ),
    ]
