# Generated by Django 4.0.3 on 2022-12-10 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0042_remove_teacher_name_teacher_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Профессор'), (2, 'Доцент'), (3, 'Старший преподователь'), (4, 'Преподователь')], verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='ped_staj',
            field=models.IntegerField(verbose_name='Пед стаж'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='shtat_sovmest',
            field=models.CharField(max_length=250, verbose_name='Штат.или совмест.'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='stavka',
            field=models.FloatField(verbose_name='Ставка'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(max_length=120, verbose_name='Звание'),
        ),
    ]
