# Generated by Django 4.0.3 on 2022-12-11 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0046_alter_teacher_zaochnoe_stavka'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='zaochnoe',
            field=models.BooleanField(default=False, verbose_name='Заочная группа'),
        ),
    ]
