# Generated by Django 4.0.3 on 2022-12-11 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0048_teacher_zaochnoe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zaochnoe',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
