# Generated by Django 4.0.3 on 2022-12-11 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0049_alter_teacher_zaochnoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='zaochnoe',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zaochnoe',
        ),
    ]
