# Generated by Django 4.0.3 on 2022-12-11 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0050_remove_group_zaochnoe_remove_teacher_zaochnoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='zaochnoe',
            field=models.BooleanField(default=False),
        ),
    ]
