# Generated by Django 4.0.3 on 2022-12-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0051_group_zaochnoe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupp',
            name='obshee_kol_stud',
        ),
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, choices=[(1, 'Академсоветник'), (2, 'Руководство кафедрой'), (3, 'Руководство деканатом'), (4, 'Руководство аспирантами и соискателями')], max_length=150, unique=True, verbose_name='Название дисциплины: '),
        ),
    ]
