# Generated by Django 4.0.3 on 2022-12-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0052_remove_groupp_obshee_kol_stud_alter_discipline_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Название дисциплины: '),
        ),
    ]
