# Generated by Django 4.0.3 on 2022-12-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0053_alter_discipline_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='rukovodstvo_dekanatom',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство деканатом'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='rukovodstvo_kafedroi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство кафедрой'),
        ),
    ]
