# Generated by Django 4.0.3 on 2022-12-14 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0063_alter_groupp_kontrol_itogovyii'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupp',
            old_name='kontrol_itogovyii',
            new_name='kontrol_itogovyi',
        ),
    ]
