# Generated by Django 4.0.3 on 2022-12-14 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0064_rename_kontrol_itogovyii_groupp_kontrol_itogovyi'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='academ_sov',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Академ. сов.'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='aspirantura_doctorontura',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Аспирантура, Докторантура'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='kontrol_tekuchiy1',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (1 контр.точка)'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='kontrol_tekuchiy2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (2 контр.точка)'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='kontrol_tekuchiy3',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/текущий (3 контр.точка)'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='magistratura',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Магистратура'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='normokontr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Нормоконтр'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='obshee_kol_stud',
            field=models.IntegerField(blank=True, null=True, verbose_name='Общее кол.студентов'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='offline',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Офлайн'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='online',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Онлайн'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='praktika_nauchno',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Научно-исследовательская'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='praktika_pedagog',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Педагогическая'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='praktika_predkval',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Предквал'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='praktika_proizvod',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Производ'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='praktika_uchebnay',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Практика/Учебная'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='priem_SRS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прием СРС'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='prochie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прочие'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='recenzirov_KR',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Рецениров_КР'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='rukovod_KRIKP',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Руковод.КРиКП'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='vsego_uchebnyh_chasov',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Всего учебных часов по расчету'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='zachita_konsult',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита вып. квал. работы/ консульт. по разделам'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='zachita_recencirovanie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита вып. квал. работы/ рецензирование'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='zachita_rukovod_VKR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита вып. квал. работы/ руководство ВКР'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='zachita_uchastie_v_GAK',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита вып. квал. работы/ участие в ГАК'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='kontrol_itogovyi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/итоговый (экзамен)'),
        ),
    ]
