# Generated by Django 4.0.3 on 2022-12-14 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0065_groupp_academ_sov_groupp_aspirantura_doctorontura_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
