# Generated by Django 4.0.3 on 2022-12-15 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0066_delete_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='za_vsego_uchebnyh_chasov',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Заочка Всего учебных часов по расчету'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='zaochnoe',
            field=models.BooleanField(default=False, verbose_name='Заочное'),
        ),
    ]
