# Generated by Django 4.0.3 on 2022-12-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0069_alter_groupp_zaochnoe'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='sovmest',
            field=models.IntegerField(blank=True, choices=[(1, 'Совместно')], null=True, verbose_name='Совместное преподование'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='is_budget',
            field=models.BooleanField(default=False, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='job_title',
            field=models.IntegerField(choices=[(1, 'Профессор'), (2, 'Доцент'), (3, 'Старший преподователь'), (4, 'Преподователь'), (5, 'зав. лаб.'), (6, 'лаборант'), (7, 'ст.лаборант'), (8, 'инженер')], verbose_name='Должность'),
        ),
    ]
