# Generated by Django 5.0.1 on 2024-02-12 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('nagr', '0070_groupp_sovmest_alter_teacher_is_budget_and_more'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Connect',
            new_name='Nagruzka',
        ),
        migrations.RemoveField(
            model_name='groupp',
            name='for_discipline',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='group_id',
            field=models.ManyToManyField(to='group.groupp', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='nagruzka',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacherr', to='teacher.teacher', verbose_name='Преподователь'),
        ),
        migrations.DeleteModel(
            name='Discipline',
        ),
        migrations.DeleteModel(
            name='Groupp',
        ),
    ]
