version: '3.9'

services:
  web:
    build: .
    container_name: nagruzkaa
    command: gunicorn main.wsgi:application --bind 0.0.0.0:8080
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
    ports:
      - "8080:8080"
    restart: always

volumes:
  static_volume: