# Generated by Django 5.0.2 on 2024-02-18 07:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название группы')),
                ('zaochnoe', models.IntegerField(choices=[(1, 'Очная'), (2, 'Заочная')], default=1, verbose_name='Форма обучения')),
                ('kol_stud_budget', models.IntegerField(blank=True, null=True, verbose_name='Кол. студ.бюджет')),
                ('kol_stud_contract', models.IntegerField(blank=True, null=True, verbose_name='Кол. студ.контракт')),
                ('obshee_kol_stud', models.IntegerField(blank=True, null=True, verbose_name='Общее кол.студентов')),
            ],
        ),
        migrations.AlterField(
            model_name='groupp',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Название группы'),
        ),
        migrations.AddField(
            model_name='groupp',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group', verbose_name='Группа'),
        ),
    ]
