# Generated by Django 5.0.2 on 2024-02-18 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0002_group_alter_groupp_name_groupp_group'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='groupp',
            options={'ordering': ('-id',), 'verbose_name': 'Группа нагрузка', 'verbose_name_plural': 'Группы нагрузки'},
        ),
    ]
