# Generated by Django 5.0.2 on 2024-02-18 08:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0003_alter_group_options_alter_groupp_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='obshee_kol_stud',
        ),
        migrations.AlterField(
            model_name='groupp',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='group.group', verbose_name='Выберите группу:'),
        ),
    ]
