# Generated by Django 5.0.2 on 2024-02-18 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0004_remove_group_obshee_kol_stud_alter_groupp_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название группы'),
        ),
    ]
