# Generated by Django 5.0.2 on 2024-05-20 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0005_alter_groupp_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ('-id',), 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
    ]
