# Generated by Django 5.0.2 on 2024-05-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0006_alter_group_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='discipline_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Дисциплины'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='obshee_kol_stud',
            field=models.FloatField(blank=True, null=True, verbose_name='Общее кол.студентов'),
        ),
    ]
