# Generated by Django 5.0.2 on 2024-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0007_alter_groupp_discipline_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groupp',
            options={'ordering': ('-id',), 'verbose_name': 'Высчитать нагрузку', 'verbose_name_plural': 'Высчитать нагрузку'},
        ),
        migrations.AlterField(
            model_name='groupp',
            name='amount_of_credit',
            field=models.IntegerField(default=0, verbose_name='Количество кредитов'),
        ),
    ]
