# Generated by Django 5.0.2 on 2024-05-22 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0008_alter_groupp_options_alter_groupp_amount_of_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='recenzirov_KR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рецениров_КР'),
        ),
        migrations.AlterField(
            model_name='groupp',
            name='rukovod_KRIKP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руковод.КРиКП'),
        ),
    ]
