# Generated by Django 5.0.2 on 2024-03-28 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='s_obhsee_kol_stud',
            new_name='s_obshee_kol_stud',
        ),
    ]
