# Generated by Django 5.0.2 on 2024-05-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0002_rename_s_obhsee_kol_stud_settings_s_obshee_kol_stud'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='recenzirov_kr',
            field=models.FloatField(default=1, verbose_name='Значение для * Рецениров_КР'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='settings',
            name='s_obshee_kol_stud',
            field=models.FloatField(verbose_name='Значение для * Общее кол.студентов'),
        ),
    ]
