# Generated by Django 5.0.1 on 2024-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('is_budget', models.BooleanField(default=False, verbose_name='Бюджет')),
                ('job_title', models.IntegerField(choices=[(1, 'Профессор'), (2, 'Доцент'), (3, 'Старший преподователь'), (4, 'Преподователь'), (5, 'зав. лаб.'), (6, 'лаборант'), (7, 'ст.лаборант'), (8, 'инженер')], verbose_name='Должность')),
                ('zvanie', models.CharField(max_length=120, verbose_name='Звание')),
                ('ped_staj', models.IntegerField(verbose_name='Пед стаж')),
                ('shtat_sovmest', models.CharField(max_length=250, verbose_name='Штат.или совмест.')),
                ('stavka', models.FloatField(verbose_name='Ставка')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
