# Generated by Django 5.0.2 on 2024-02-17 09:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doljnost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('stavka', models.IntegerField(verbose_name='Ставка')),
            ],
            options={
                'verbose_name': 'Должность',
                'verbose_name_plural': 'Должности',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('is_budget', models.BooleanField(default=False, verbose_name='Бюджет')),
                ('is_not_budget', models.BooleanField(default=False, verbose_name='Не бюджет')),
                ('zvanie', models.CharField(max_length=120, verbose_name='Звание')),
                ('ped_staj', models.IntegerField(verbose_name='Пед стаж')),
                ('shtat_sovmest', models.CharField(max_length=250, verbose_name='Штат.или совмест.')),
                ('stavka', models.FloatField(verbose_name='Ставка')),
                ('stavka_budget', models.FloatField(default=0, verbose_name='Ставка для бюджета')),
                ('job_title', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teacher.doljnost', verbose_name='Должность')),
            ],
            options={
                'verbose_name': 'Преподователь',
                'verbose_name_plural': 'Преподователи',
                'ordering': ('-id',),
            },
        ),
    ]
