# Generated by Django 5.0.2 on 2024-05-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='is_not_budget',
        ),
        migrations.AddField(
            model_name='teacher',
            name='stavka_zaoch',
            field=models.FloatField(default=0, verbose_name='Ставка заочное'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='vsego_stavka',
            field=models.FloatField(default=0, verbose_name='Всего ставка'),
        ),
    ]
