# Generated by Django 5.0.2 on 2024-05-21 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_remove_teacher_is_not_budget_teacher_stavka_zaoch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='vsego_stavka',
        ),
        migrations.AlterField(
            model_name='doljnost',
            name='stavka',
            field=models.IntegerField(verbose_name='Количество часов'),
        ),
    ]
