# Generated by Django 5.0.2 on 2024-05-21 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_remove_teacher_vsego_stavka_alter_doljnost_stavka'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',), 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='stavka_zaoch',
        ),
    ]
