# Generated by Django 5.0.2 on 2024-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_alter_teacher_options_remove_teacher_stavka_zaoch'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('-id',), 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.AddField(
            model_name='teacher',
            name='ordering_field',
            field=models.FloatField(default=0, verbose_name='Поле для сортировки'),
        ),
    ]
