# Generated by Django 5.0.2 on 2024-05-22 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_alter_teacher_options_teacher_ordering_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('id',), 'verbose_name': 'Преподователь', 'verbose_name_plural': 'Преподователи'},
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ordering_field',
        ),
    ]
