# Generated by Django 5.0.1 on 2024-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=150, unique=True, verbose_name='Название дисциплины: ')),
                ('amount_of_credit', models.IntegerField(verbose_name='Количество кредитов')),
                ('is_kursovoi', models.BooleanField(default=False, verbose_name='Курсовой')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
