# Generated by Django 4.1.2 on 2022-10-23 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0011_alter_groupp_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discipline',
            name='name',
            field=models.CharField(blank=True, max_length=150, verbose_name='Название дисциплины: '),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=250, verbose_name='ФИО преподователя: '),
        ),
    ]
