# Generated by Django 4.0.3 on 2022-10-30 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0020_alter_discipline_is_kursovoi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='group_id', to='nagr.teacher', verbose_name='Выберите преподователя'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='name_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagr.groupp', verbose_name='Выберите группу'),
        ),
    ]
