# Generated by Django 4.0.3 on 2022-11-04 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0025_alter_discipline_options_alter_group_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='academ_sov',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='aspi_doctoron',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='itogo',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='itogo2',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='itogo_kontr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='itogo_pochasovoi',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='itovyi',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='laby',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='lekcii',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='magistratura',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='normokontr',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='ofline',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='online',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pochasovoi',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='pochasovoi_fond_kontract',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika_nauchno',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika_pedagog',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika_predkval',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika_proizvod',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='praktika_ucheb',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='priem_SRS',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='recenzirov_KR',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rikovod_dek',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rukovod_KRIKP',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='rukovod_kaf',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='vsego',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zachita_consult',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zachita_recenzirovanie',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zachita_rukovod_VKR',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='zachita_uchastie',
        ),
        migrations.AddField(
            model_name='connect',
            name='academ_sov',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Академ. сов'),
        ),
        migrations.AddField(
            model_name='connect',
            name='aspi_doctoron',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Аспирантура, докторонтура'),
        ),
        migrations.AddField(
            model_name='connect',
            name='itogo',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итого по бюджету'),
        ),
        migrations.AddField(
            model_name='connect',
            name='itogo2',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ИТОГО'),
        ),
        migrations.AddField(
            model_name='connect',
            name='itogo_kontr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итого по контракту'),
        ),
        migrations.AddField(
            model_name='connect',
            name='itogo_pochasovoi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ИТОГО почасовой фонд'),
        ),
        migrations.AddField(
            model_name='connect',
            name='itovyi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Итоговый (экзамен)'),
        ),
        migrations.AddField(
            model_name='connect',
            name='laby',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Лабораторные'),
        ),
        migrations.AddField(
            model_name='connect',
            name='lekcii',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Лекции'),
        ),
        migrations.AddField(
            model_name='connect',
            name='magistratura',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Магистратура'),
        ),
        migrations.AddField(
            model_name='connect',
            name='normokontr',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Нормоконтр'),
        ),
        migrations.AddField(
            model_name='connect',
            name='ofline',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Офлайн'),
        ),
        migrations.AddField(
            model_name='connect',
            name='online',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Онлайн'),
        ),
        migrations.AddField(
            model_name='connect',
            name='pochasovoi',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Почасовой фонд бюджет'),
        ),
        migrations.AddField(
            model_name='connect',
            name='pochasovoi_fond_kontract',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Почасвой фонд контракт'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практические'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika_nauchno',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Научно-исследовательская'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika_pedagog',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Педагогическая'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika_predkval',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Предквалификационная'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika_proizvod',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Производственная'),
        ),
        migrations.AddField(
            model_name='connect',
            name='praktika_ucheb',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Практика/Учебная'),
        ),
        migrations.AddField(
            model_name='connect',
            name='priem_SRS',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Прием СРС'),
        ),
        migrations.AddField(
            model_name='connect',
            name='recenzirov_KR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Рецензиров. КР'),
        ),
        migrations.AddField(
            model_name='connect',
            name='rikovod_dek',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство деканатом'),
        ),
        migrations.AddField(
            model_name='connect',
            name='rukovod_KRIKP',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руковод. КРиКП'),
        ),
        migrations.AddField(
            model_name='connect',
            name='rukovod_kaf',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Руководство кафедрой'),
        ),
        migrations.AddField(
            model_name='connect',
            name='vsego',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Всего'),
        ),
        migrations.AddField(
            model_name='connect',
            name='zachita_consult',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/консульт. по разделам'),
        ),
        migrations.AddField(
            model_name='connect',
            name='zachita_recenzirovanie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/рецензирование'),
        ),
        migrations.AddField(
            model_name='connect',
            name='zachita_rukovod_VKR',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/Руководство ВКР'),
        ),
        migrations.AddField(
            model_name='connect',
            name='zachita_uchastie',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Защита  выпю квал. работы/участие в ГАК'),
        ),
    ]
