# Generated by Django 4.0.3 on 2022-11-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0026_remove_teacher_academ_sov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='connect',
            name='doljnost',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность'),
        ),
        migrations.AddField(
            model_name='connect',
            name='last_name',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='ФИО'),
        ),
    ]
