# Generated by Django 4.0.3 on 2022-12-04 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0030_remove_connect_itogo_remove_connect_itogo2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connect',
            name='shtatnye_budget',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='shtatnye_contract_ochnoe',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='shtatnye_contract_zaochnoe',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='shtatnye_vsego',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='ucheb_budget',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='ucheb_contract_ochnoe',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='ucheb_contract_zaochnoe',
        ),
        migrations.RemoveField(
            model_name='connect',
            name='ucheb_vsego',
        ),
        migrations.AddField(
            model_name='teacher',
            name='ped_staj',
            field=models.IntegerField(default=0, verbose_name='Пед стаж'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='shtat_sovmest',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Штат.или совмест.'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='stavka',
            field=models.FloatField(blank=True, null=True, verbose_name='Ставка'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Звание'),
        ),
        migrations.CreateModel(
            name='Coppect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, max_length=250, null=True, verbose_name='Должность')),
                ('zvanie', models.CharField(blank=True, max_length=250, null=True, verbose_name='Звание')),
                ('ped_staj', models.IntegerField(default=0, verbose_name='Пед стаж')),
                ('shtat_sovmest', models.CharField(blank=True, max_length=250, null=True, verbose_name='Штат.или совмест.')),
                ('stavka', models.FloatField(blank=True, null=True, verbose_name='Ставка')),
                ('shtatnye_budget', models.FloatField(default=0, verbose_name='Штатные единицы/Бюджет')),
                ('shtatnye_contract_ochnoe', models.FloatField(default=0, verbose_name='Штатные единицы/контракт/очное')),
                ('shtatnye_contract_zaochnoe', models.FloatField(default=0, verbose_name='Штатные единицы/контракт/заочное')),
                ('ucheb_budget', models.FloatField(default=0, verbose_name='Учебная нагрузка/Бюджет')),
                ('ucheb_contract_ochnoe', models.FloatField(default=0, verbose_name='Учебная нагрузка/контракт/очное')),
                ('ucheb_contract_zaochnoe', models.FloatField(default=0, verbose_name='Учебная нагрузка/контракт/заочное')),
                ('group_id', models.ManyToManyField(to='nagr.group', verbose_name='Группа')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nagr.teacher', verbose_name='Преподователь')),
            ],
        ),
    ]
