# Generated by Django 4.0.3 on 2022-12-04 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0031_remove_connect_shtatnye_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coppect',
            name='name',
            field=models.CharField(default=0, max_length=250, verbose_name='ФИО преподователя: '),
            preserve_default=False,
        ),
    ]
