# Generated by Django 4.0.3 on 2022-12-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0059_alter_connect_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='kontrol_itogovy',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/итоговый (экзамен)'),
        ),
    ]
