# Generated by Django 4.0.3 on 2022-12-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0061_remove_groupp_kontrol_itogovy'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupp',
            name='kontrol_itogovyii',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Контроль/итоговый (экзамен)'),
        ),
    ]
