# Generated by Django 4.0.3 on 2022-12-17 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0068_remove_teacher_zaochnoe_stavka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupp',
            name='zaochnoe',
            field=models.IntegerField(choices=[(1, 'Очная'), (2, 'Заочная')], default=1, verbose_name='Форма обучения'),
        ),
    ]
