# Generated by Django 4.0.3 on 2022-12-22 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0071_teacher_get_timee'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='get_full_namee',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='get_job_title',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='get_stavka',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='get_za_stavka',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
