# Generated by Django 4.0.3 on 2022-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0072_teacher_get_full_namee_teacher_get_job_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.CharField(choices=[(1, 'д.ф.-м.н.'), (2, 'д.т.н.'), (3, 'к.ф.-м.н.'), (4, 'к.т.н.')], max_length=10, verbose_name='Звание'),
        ),
    ]
