# Generated by Django 4.0.3 on 2022-12-22 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0073_alter_teacher_zvanie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.IntegerField(choices=[(1, 'д.ф.-м.н.'), (2, 'д.т.н.'), (3, 'к.ф.-м.н.'), (4, 'к.т.н.')], verbose_name='Звание'),
        ),
    ]
