# Generated by Django 4.0.3 on 2022-12-22 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0074_alter_teacher_zvanie'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='zvaniiee',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
