# Generated by Django 4.0.3 on 2022-12-28 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nagr', '0075_teacher_zvaniiee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='get_timee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='zvanie',
            field=models.IntegerField(choices=[(1, 'д.ф.-м.н.'), (2, 'д.т.н.'), (3, 'к.ф.-м.н.'), (4, 'к.т.н.'), (5, 'нет званий')], verbose_name='Звание'),
        ),
    ]
